# Generated by Django 6.0.4 on 2026-04-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_options_remove_expense_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Banco/Conta')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Atual')),
                ('color', models.CharField(default='#8a2be2', help_text='Código Hex da cor', max_length=7)),
            ],
            options={
                'verbose_name': 'Conta/Banco',
                'verbose_name_plural': 'Contas/Bancos',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Dívida')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pago')),
                ('debt_type', models.CharField(choices=[('FIXA', 'Fixa'), ('TEMP', 'Temporária')], default='TEMP', max_length=4)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('PAID', 'Paga')], default='ACTIVE', max_length=6)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
            ],
            options={
                'verbose_name': 'Dívida',
                'verbose_name_plural': 'Dívidas',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('transaction_type', models.CharField(choices=[('IN', 'Receita (Entrada)'), ('OUT', 'Despesa (Saída)')], default='OUT', max_length=3)),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Notas adicionais')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='expenses.account', verbose_name='Conta/Banco')),
                ('debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='expenses.debt', verbose_name='Vincular a Dívida')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
