# Generated by Django 6.0.4 on 2026-04-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_account_debt_transaction_delete_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='creditor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Credor (Para quem deve?)'),
        ),
    ]
