# Generated by Django 6.0.4 on 2026-04-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_debt_creditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID da Transação'),
        ),
    ]
