# Generated by Django 6.0.4 on 2026-04-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_transaction_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='identifier',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ID da Transação'),
        ),
    ]
